### ISSUE TITLE
rawCollection not defined

### ISSUE THREAD

**Issue by dmarkrollins** [Konecty/meteor-mongo-counter#3]
I am running Meteor 1.1 and see no method rawCollection 

Exception while invoking method 'insertBracket' TypeError: Object bracket_counter has no method 'rawCollection'
I20150402-06:08:22.742(-4)?     at getCounterCollection (packages/konecty:mongo-counter/counter.coffee:2:14)
I20150402-06:08:22.743(-4)?     at callCounter (packages/konecty:mongo-counter/counter.coffee:6:14)
I20150402-06:08:22.743(-4)?     at _incrementCounter (packages/konecty:mongo-counter/counter.coffee:20:12)
I20150402-06:08:22.743(-4)?     at [object Object].Meteor.methods.insertBracket (app/server/methods/bracketMethods.js:25:15)
I20150402-06:08:22.743(-4)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150402-06:08:22.744(-4)?     at packages/ddp/livedata_server.js:648:1
I20150402-06:08:22.744(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150402-06:08:22.744(-4)?     at packages/ddp/livedata_server.js:647:1
I20150402-06:08:22.744(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150402-06:08:22.744(-4)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)

I am using it like so:

Brackets.insert(
        {
            bracketId: incrementCounter(COUNTER_BRACKET),
...

**Comment by dmarkrollins** [comment]
When I pass in the subscription reference as the first parm it works fine but that does not match the api docs.
