### ISSUE TITLE
Error...

### ISSUE THREAD

**Issue by joetidee** [Konecty/meteor-mongo-counter#5]
I am running this ...

```
getNextSequence: function () {
    incrementCounter('box_id', 1); 
}
```

as a meteor method using...

```
Meteor.call('getNextSequence');
```

I get the following errors in my terminal...

```
Exception while invoking method 'getNextSequence' TypeError: Object box_id has no method 'rawCollection'
I20150508-19:33:23.698(0)?     at getCounterCollection (packages/konecty:mongo-counter/counter.coffee:2:14)
I20150508-19:33:23.698(0)?     at callCounter (packages/konecty:mongo-counter/counter.coffee:6:14)
I20150508-19:33:23.698(0)?     at _incrementCounter (packages/konecty:mongo-counter/counter.coffee:20:12)
I20150508-19:33:23.698(0)?     at [object Object].Meteor.methods.getNextSequence (app/server/methods.js:41:16)
I20150508-19:33:23.698(0)?     at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:160:1)
I20150508-19:33:23.699(0)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150508-19:33:23.699(0)?     at packages/ddp/livedata_server.js:648:1
I20150508-19:33:23.699(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150508-19:33:23.699(0)?     at packages/ddp/livedata_server.js:647:1
I20150508-19:33:23.699(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
```

**Comment by sampaiodiego** [comment]
hey joetidee, yout can't pass the collection name anymore. you have to pass the collection object. Something like this:

``` javascript
var myCollection = new Meteor.Collection('collectionName');
var newSequentialCode = incrementCounter(myCollection, 'code', 1);
```

I'm sorry for not updating documentation.

**Comment by sampaiodiego** [comment]
The docs were updated.
